version: "3.8"
services:
  socialapi:
    build: ./socialAPI
    ports:
      - "3500:3500"
    networks:
      - social-network
    depends_on:
      - authapi

  authapi:
    build: ./authAPI
    ports:
      - "9000:9000"
    networks:
      - social-network

networks:
  social-network: